name: Common Workflow

on: workflow_call

jobs:
  checkout-and-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Read File
        run: |
          echo "Reading file from ${{ inputs.file_path }}"
          cat ${{ inputs.file_path }}