name: Pipeline

on:
  push:
    branches:
      - master # Trigger push on "master" branch

jobs:
    # Android jobs
    Android-CreateProduct: # Job name
      uses: ThangNguyen0495/Reusable/.github/workflows/androidAppiumConfigs.yml@main
      with:
        appium_port: "4723" # Appium server port
        artifact: ""
        test_name: "Android-CreateProduct" # Report artifact
        test_config: "test_config/android/seller/productManagementTest.xml" # Test config path

#   # iOS jobs
#    IOS-CreateProduct:
#      uses: ThangNguyen0495/Reusable/.github/workflows/iosAppiumConfigs.yml@main
#      with:
#        appium_port: "4724"
#        artifact: ""
#        test_name: "IOS-CreateProduct"
#        test_config: "test_xml/iOS/createProductTest.xml"
#
#    # Selenium job
#    Dashboard-UpdateProduct:
#      uses: ThangNguyen0495/Reusable/.github/workflows/seleniumConfigs.yml@main
#      with:
#        artifact: ""
#        test_name: "Dashboard-UpdateProduct"
#        test_config: "test_config/web/updateProductTest.xml"

  #  Dashboard-ProductManagement:
  #    needs:
  #      - Dashboard-CreateProduct
  #      - Dashboard-UpdateProduct
  #
  #    if: always()
  #    uses: ThangNguyen0495/Reusable/.github/workflows/seleniumConfigs.yml@main
  #    with:
  #      test_name: "Dashboard-ProductManagement"
  #      test_config: "test_config/web/productManagementTest.xml"
  #      branch_name: "GoSELL-Thang"
  #
  #  Storefront-ProductDetail-NormalxWithoutVariation:
  #    needs: CloneGit
  #    uses: ThangNguyen0495/Reusable/.github/workflows/seleniumConfigs.yml@main
  #    with:
  #      test_name: "Storefront-ProductDetail-NormalxWithoutVariation"
  #      test_config: "test_config/web/productDetail_Normal_withoutVariation.xml"
  #      branch_name: "GoSELL-Thang"

  #  Storefront-ProductDetail-IMEIxWithoutVariation:
  #    needs: CloneGit
  #    uses: ThangNguyen0495/Reusable/.github/workflows/seleniumConfigs.yml@main
  #    with:
  #      test_name: "Storefront-ProductDetail-IMEIxWithoutVariation"
  #      test_config: "test_config/web/productDetail_IMEI_withoutVariation.xml"
  #      branch_name: "GoSELL-Thang"

  #  Storefront-ProductDetail-NormalxVariation:
  #    needs: CloneGit
  #    uses: ThangNguyen0495/Reusable/.github/workflows/seleniumConfigs.yml@main
  #    with:
  #      test_name: "Storefront-ProductDetail-NormalxVariation"
  #      test_config: "test_config/web/productDetail_Normal_Variation.xml"
  #      branch_name: "GoSELL-Thang"

  #  Storefront-ProductDetail-IMEIxVariation:
  #    needs: CloneGit
  #    uses: ThangNguyen0495/Reusable/.github/workflows/seleniumConfigs.yml@main
  #    with:
  #      test_name: "Storefront-ProductDetail-IMEIxVariation"
  #      test_config: "test_config/web/productDetail_IMEI_Variation.xml"
  #      branch_name: "GoSELL-Thang"

  #  Storefront-ProductDetail-Promotion:
  #    needs:
  #      - Storefront-ProductDetail-NormalxWithoutVariation
  #      - Storefront-ProductDetail-IMEIxWithoutVariation
  #      - Storefront-ProductDetail-NormalxVariation
  #      - Storefront-ProductDetail-IMEIxVariation
  #
  #    if: always()
  #    uses: ThangNguyen0495/Reusable/.github/workflows/seleniumConfigs.yml@main
  #    with:
  #      test_name: "Storefront-ProductDetail-Promotion"
  #      test_config: "test_config/web/productDetail_combinePromotion.xml"
  #      branch_name: "GoSELL-Thang"

  #  Android-GoSELLER-CreateProduct:
  #    needs: CloneGit
  #    uses: ThangNguyen0495/Reusable/.github/workflows/androidAppiumConfigs.yml@main
  #    with:
  #      appium_port: "4723"
  #      test_name: "Android-GoSELLER-CreateProduct"
  #      test_config: "test_config/android/seller/createProductTest.xml"
  #      branch_name: "GoSELL-Thang"

  #  Android-GoSELLER-UpdateProduct:
  #    needs: CloneGit
  #    uses: ThangNguyen0495/Reusable/.github/workflows/androidAppiumConfigs.yml@main
  #    with:
  #      appium_port: "4724"
  #      test_name: "Android-GoSELLER-UpdateProduct"
  #      test_config: "test_config/android/seller/editProductTest.xml"
  #      branch_name: "GoSELL-Thang"

#  Android-GoSELLER-ProductManagement:
#    needs: CloneGit
#    #      - Android-GoSELLER-CreateProduct
#    #      - Android-GoSELLER-UpdateProduct
#    #    if: always()
#    uses: ThangNguyen0495/Reusable/.github/workflows/androidAppiumConfigs.yml@main
#    with:
#      appium_port: "4725"
#      test_name: "Android-GoSELLER-ProductManagement"
#      test_config: "test_config/android/seller/productManagementTest.xml"
#      branch_name: "GoSELL-Thang"
  #
  #  IOS-GoSELLER-CreateProduct:
  #    needs: CloneGit
  #    uses: ThangNguyen0495/Reusable/.github/workflows/iosAppiumConfigs.yml@main
  #    with:
  #      appium_port: "4726"
  #      test_name: "IOS-GoSELLER-CreateProduct"
  #      test_config: "test_config/iOS/seller/createProductTest.xml"
  #      branch_name: "GoSELL-Thang"
  #
  #  IOS-GoSELLER-UpdateProduct:
  #    needs: CloneGit
  #    if: always()
  #    uses: ThangNguyen0495/Reusable/.github/workflows/iosAppiumConfigs.yml@main
  #    with:
  #      appium_port: "4727"
  #      test_name: "IOS-GoSELLER-UpdateProduct"
  #      test_config: "test_config/iOS/seller/editProductTest.xml"
  #      branch_name: "GoSELL-Thang"
  #
#  IOS-GoSELLER-ProductManagement:
#    needs: CloneGit
    #      - IOS-GoSELLER-CreateProduct
    #      - IOS-GoSELLER-UpdateProduct
    #    if: always()
#    uses: ThangNguyen0495/Reusable/.github/workflows/iosAppiumConfigs.yml@main
#    with:
#      appium_port: "4728"
#      test_name: "IOS-GoSELLER-ProductManagement"
#      test_config: "test_config/iOS/seller/productManagementTest.xml"
#      branch_name: "GoSELL-Thang"


#  CleanJob:
#    runs-on: ubuntu-20.04
#    needs:
#      #      - Dashboard-ProductManagement
#      #      - Storefront-ProductDetail-Promotion
#      - Android-GoSELLER-ProductManagement
##      - IOS-GoSELLER-ProductManagement
#
#    if: always()
#    steps:
#      - name: Delete clone repository
#        uses: geekyeggo/delete-artifact@v5
#        with:
#          name: ClonedRepository

