name: iOS Appium Tests

on: [ push, pull_request ]

jobs:
  build:
    runs-on: macos-latest

    env:
      CI: true
      APPIUM_TEST_SERVER_PORT: 4723
      APPIUM_TEST_SERVER_HOST: 0.0.0.0

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '22'

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install Appium
        run: npm install -g appium

      - name: Install Xcode command-line tools
        run: xcode-select --install || true

      - name: Install Carthage
        run: brew install carthage

      # Check available Xcode versions
      - name: Check available Xcode versions
        run: ls /Applications/

      # Use the correct path or the default
      - name: Set Xcode version
        run: sudo xcode-select --switch /Applications/Xcode.app

      - name: Start iOS Simulator
        id: start_simulator
        run: |
          RUNTIME=$(xcrun simctl list runtimes | grep 'iOS 16.4' | awk '{print $NF}' | tr -d '()')
          UDID=$(xcrun simctl create "TestSimulator" com.apple.CoreSimulator.SimDeviceType.iPhone-13 $RUNTIME)
          xcrun simctl boot $UDID
          echo "SIMULATOR_UDID=$UDID" >> $GITHUB_ENV

      - name: Start Appium server
        run: |
          cwd=$(pwd)
          pushd "$cwd"
          cd ~
          appium driver install uiautomator2
          appium driver doctor uiautomator2
          nohup appium -a $APPIUM_TEST_SERVER_HOST -p $APPIUM_TEST_SERVER_PORT -pa /wd/hub > appium_log.txt 2>&1 &
          tail -f appium_log.txt &
          popd

      - name: Install dependencies
        run: |
          mvn install -DskipTests

      - name: Run Tests
        run: mvn test "-Dsurefire.suiteXmlFiles=testng.xml"

      - name: Upload Test Reports
        uses: actions/upload-artifact@v3
        with:
          name: Test-Reports
          path: test-output/
