name: Dependent Jobs Workflow

on:
  push:
    branches:
      - master

jobs:
  jobB:
    uses: ./.github/workflows/common.yml
    with:
      file_path: '.github/workflows/iOS_maven.yml'

  jobA:
    needs: jobB
    uses: ./.github/workflows/common.yml
    with:
      file_path: '.github/workflows/iOS_maven.yml'

  jobC:
    needs: [jobA, jobB]
    uses: ./.github/workflows/common.yml
    with:
      file_path: '.github/workflows/iOS_maven.yml'
