name: Android Tests on Windows

on:
  push:
    branches:
      - Dev
  pull_request:
    branches:
      - Dev

jobs:
  test:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Download Genymotion
        run: |
          echo "Downloading Genymotion..."
          curl -LO https://dl.genymotion.com/releases/genymotion-3.2.1/genymotion-3.2.1-vbox.exe
          echo "Genymotion download completed."

      - name: Install Genymotion
        run: |
          echo "Installing Genymotion..."
          Start-Process -Wait -FilePath .\genymotion-3.2.1-vbox.exe -ArgumentList '/S'
          echo "Genymotion installation completed."

      - name: Verify Genymotion Installation
        run: |
          if (Test-Path "C:\Program Files\Genymobile\Genymotion\genymotion.exe") {
            echo "Genymotion installed successfully."
          } else {
            echo "Genymotion installation failed."
            exit 1
          }

      - name: Start Genymotion Emulator
        run: |
          echo "Starting Genymotion emulator..."
          Start-Process -FilePath "C:\Program Files\Genymobile\Genymotion\player" -ArgumentList '--vm-name "Your_Emulator_Name"' -PassThru -Wait
          echo "Genymotion emulator started."

      - name: Install Android SDK
        run: |
          echo "Installing Android SDK..."
          choco install -y android-sdk
          choco install -y android-sdk-tools
          choco install -y android-ndk
          echo "Android SDK installation completed."

      - name: Install Android dependencies
        run: |
          echo "Installing Android dependencies..."
          sdkmanager --install "platform-tools" "platforms;android-30" "build-tools;30.0.3"
          echo "Android dependencies installation completed."

      - name: Build and test
        run: |
          echo "Building and testing the project..."
          mvn clean install
          mvn test
          echo "Build and tests completed."
