name: Main Workflow
on:
  push:
    branches:
      - master

jobs:
  jobA:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout the current repository
        run: echo "Job A"

      - name: Enable KVM group perms
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      - name: Install SDK
        run: |
          wget https://dl.google.com/android/repository/commandlinetools-linux-6200805_latest.zip
          mkdir -p Android/Sdk
          unzip commandlinetools-linux-6200805_latest.zip -d Android/Sdk

      - name: Set environment
        run: |
          export ANDROID_HOME=$HOME/Android/Sdk
          export PATH="$ANDROID_HOME/emulator:$ANDROID_HOME/tools:$ANDROID_HOME/tools/bin:$ANDROID_HOME/platform-tools:$PATH"


      - name: Check list AVDs
        run: |
          cd $ANDROID_HOME/emulator
          ./emulator -list-avds
