name: Main Workflow
on:
  push:
    branches:
      - master

jobs:
  jobA:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout the current repository
        run: echo "Job A"
        
  call-reusable:
    needs: jobA
    uses: ./.github/workflows/common.yml
    with:
      name: "GitHub Actions"
