name: Android Emulator Setup

on:
  push:
    branches:
      - master

jobs:
  setup-android-sdk:
    name: Setup Android SDK and Create Emulator
    runs-on: ubuntu-latest

    steps:
      - name: Set up JDK 22
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '22'

      - name: Create and start emulator
        uses: ThangNguyen0495/Customs@v1.3.3


