 - name: Set up Android SDK
      run: |
        echo y | "${env:ANDROID_HOME}\tools\bin\sdkmanager" "platform-tools" "platforms;android-30" "emulator" "system-images;android-30;google_apis;x86_64"
      env:
        JAVA_HOME: ${{ steps.setup-java.outputs.path }}
        ANDROID_HOME: ${{ env.ANDROID_HOME }}
      shell: powershell

    - name: Create AVD
      run: |
        "${env:ANDROID_HOME}\tools\bin\avdmanager" create avd -n test -k "system-images;android-30;google_apis;x86_64" --device "Nexus 6"
      env:
        JAVA_HOME: ${{ steps.setup-java.outputs.path }}
        ANDROID_HOME: ${{ env.ANDROID_HOME }}
      shell: powershell

    - name: Start emulator
      run: |
        start /B emulator -avd test -no-window -no-snapshot -no-boot-anim -no-audio
        adb wait-for-device
        adb shell input keyevent 82
      env:
        JAVA_HOME: ${{ steps.setup-java.outputs.path }}
        ANDROID_HOME: ${{ env.ANDROID_HOME }}
      shell: powershell

    - name: Install dependencies
      run: mvn clean install -DskipTests
      env:
        JAVA_HOME: ${{ steps.setup-java.outputs.path }}
      shell: powershell

    - name: Start Appium server
      run: npx appium --relaxed-security &
      env:
        JAVA_HOME: ${{ steps.setup-java.outputs.path }}
      shell: powershell

    - name: Run tests
      run: mvn test
      env:
        JAVA_HOME: ${{ steps.setup-java.outputs.path }}
      shell: powershell
