name: Android Emulator Test on Windows

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: Set JAVA_HOME
      run: echo "JAVA_HOME=${{ steps.setup-java.outputs.path }}" >> $GITHUB_ENV

    - name: Set up Android SDK
      run: |
        & "${env:ANDROID_HOME}\tools\bin\sdkmanager.bat" "platform-tools" "platforms;android-30" "emulator" "system-images;android-30;google_apis;x86_64"
      env:
        JAVA_HOME: ${{ steps.setup-java.outputs.path }}
        ANDROID_HOME: ${{ env.ANDROID_HOME }}
      shell: powershell

    - name: Create AVD
      run: |
        & "${env:ANDROID_HOME}\tools\bin\avdmanager.bat" create avd -n test -k "system-images;android-30;google_apis;x86_64" --device "Nexus 6"
      env:
        JAVA_HOME: ${{ steps.setup-java.outputs.path }}
        ANDROID_HOME: ${{ env.ANDROID_HOME }}
      shell: powershell

    - name: Start emulator
      run: |
        start /B emulator -avd test -no-window -no-snapshot -no-boot-anim -no-audio
        adb wait-for-device
        adb shell input keyevent 82
      shell: powershell
      env:
        JAVA_HOME: ${{ steps.setup-java.outputs.path }}
        ANDROID_HOME: ${{ env.ANDROID_HOME }}

    - name: Install dependencies
      run: mvn clean install -DskipTests
      shell: powershell
      env:
        JAVA_HOME: ${{ steps.setup-java.outputs.path }}

    - name: Start Appium server
      run: npx appium --relaxed-security &
      shell: powershell
      env:
        JAVA_HOME: ${{ steps.setup-java.outputs.path }}

    - name: Run tests
      run: mvn test
      shell: powershell
      env:
        JAVA_HOME: ${{ steps.setup-java.outputs.path }}
