name: Upload and Delete Artifact Workflow

on: [push]

jobs:
  jobA:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
  
      - name: Create test file
        run: echo hello > test.txt
  
      - uses: actions/upload-artifact@v4
        with:
            name: my-artifact
            path: test.txt
  jobB:
    runs-on: ubuntu-latest
    steps:
      - uses: geekyeggo/delete-artifact@v5
        with:
            name: my-artifact
